@startuml

interface MQAdmin{
}

interface MQProducer{
public void start()
public SendResult send( Message msg)
}

class ClientConfig{
}

class DefaultMQProducer{
}
note right:这里是入口类

class Message{
    - String topic;
    - int flag;
    - Map<String, String> properties;
    - byte[] body;
    - String transactionId;
}
DefaultMQProducer-->Message
note right
发送的消息
topic是发送目标topic
body是发送的数据
end note

class MessageQueue{
    - String topic;
    - String brokerName;
    - int queueId;
}
DefaultMQProducer-->MessageQueue
class DefaultMQProducerImpl{

}

class MQClientInstance {
 MQClientAPIImpl mQClientAPIImpl
}

class MQClientAPIImpl{
RemotingClient remotingClient
}
note right:这里实际启动netty

MQClientInstance -- MQClientAPIImpl

MQClientAPIImpl -- RemotingClient

interface RemotingClient{
}

abstract class NettyRemotingAbstract{

}

class NettyRemotingClient{
}
RemotingClient<|--NettyRemotingClient
NettyRemotingAbstract <|--NettyRemotingClient


MQAdmin <|.. MQProducer
MQProducer <|.. DefaultMQProducer
ClientConfig <|-- DefaultMQProducer
DefaultMQProducer -- DefaultMQProducerImpl
DefaultMQProducerImpl ..> MQClientInstance


@enduml